apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-g2cv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-g2cv
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-g2cv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-g2cv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-g2cv
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jtdp-tenant/rhtap-demo-app/hacbs-test-project-g2cv@sha256:ec8014429b3a84f464be7c55f0bcc294f733aeac0ffd3f616953b3a60c05544f
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
