apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-g2cv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jtdp-tenant/rhtap-demo-app/hacbs-test-project-g2cv@sha256:ec8014429b3a84f464be7c55f0bcc294f733aeac0ffd3f616953b3a60c05544f
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
